backend:
  name: github
  repo: karisakib/portfolio # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create - {{collection}} - "{{slug}}"
    update: Update - {{collection}} - "{{slug}}"
    delete: Delete - {{collection}} - "{{slug}}"
    uploadMedia: Upload - "{{path}}"
    deleteMedia: Delete - "{{path}}"
    openAuthoring: "{{message}}"

site_url: https://karisakib.com/
logo_url: https://karisakib.com/images/profile_photo.png

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

media_folder: "content/static/images/uploads"
# public_folder: "/images/uploads"

media_library:
  name: uploadcare

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        # extension: "json"
        # format: "json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "About Page"
        name: "about"
        file: "content/about.json"
        # extension: "json"
        # format: "json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Locations
            name: locations
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Address, name: address, widget: string }

  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    extension: "json"
    media_folder: "content/static/images/uploads"
    # public_folder: "/images/uploads"
    # filter: { field: visibleInCMS, value: true }
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Date, name: date, widget: datetime, date_format: "MMMM D, YYYY" }
      - label: Paragraphs
        name: paragraphs
        widget: object
        fields:
          - { label: Paragraph, name: paragraph, widget: text }
          - { label: Code Block, name: code_block, widget: code, required: false }
          - { label: Section Image, name: image, widget: "image", required: false }

  - label: "Books"
    name: "books"
    folder: "content/books"
    create: true
    slug: "{{slug}}"
    extension: "json"
    media_folder: "content/static/images/uploads"
    # public_folder: "/images/uploads"
    # filter: { field: visibleInCMS, value: true }
    fields:
      - { label: Title, name: title, widget: string, required: true }
      - { label: Author, name: author, widget: string, required: true }
      - { label: Slug, name: slug, widget: string, required: true }
      - { label: Review, name: review, widget: string, required: true }
      - label: Notes
        name: notes
        widget: list
        field:
          - { label: Note, name: note, widget: text }

  - label: "Resources"
    name: "resources"
    folder: "content/resources"
    create: true
    slug: "{{slug}}"
    extension: "json"
    media_folder: "content/static/images/uploads"
    # public_folder: "/images/uploads"
    # filter: { field: visibleInCMS, value: true }
    fields:
      - { label: Section Header, name: section_header, widget: string }
      - label: Resources
        name: resources
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - { label: URL", name: url, widget: string }
          - { label: Description, name: description, widget: text }
      - label: Books
        name: books
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - { label: URL", name: url, widget: string }
          - { label: Description, name: description, widget: text }
