backend:
  name: github
  repo: karisakib/portfolio # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create - {{collection}} - "{{slug}}"
    update: Update - {{collection}} - "{{slug}}"
    delete: Delete - {{collection}} - "{{slug}}"
    uploadMedia: Upload - "{{path}}"
    deleteMedia: Delete - "{{path}}"
    openAuthoring: "{{message}}"

site_url: https://karisakib.com/
logo_url: https://karisakib.com/images/profile_photo.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

media_folder: "content/static/images/uploads"
public_folder: "/images/uploads"

media_library:
  name: uploadcare
  # config:
  #   cloud_name: your-cloud-name
  #   api_key: your-api-key
  #   api_secret: your-api-secret

collections:
  - label: "Pages"
    name: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
      - label: "About Page"
        name: "about"
        file: "content/about.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Locations
            name: locations
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Address, name: address, widget: string }

  - label: "Blog"
    name: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    media_folder: "content/static/images/uploads"
    public_folder: "/images/uploads"
    filter: { field: visibleInCMS, value: true }
    fields:
      - { name: title, widget: string }
      - { name: slug, widget: hidden, default: "{{slug}}" }
      - { name: description, widget: string }
      - { name: date, widget: datetime, date_format: "MMMM D, YYYY" }
      - { name: body, widget: markdown }
